#!/usr/bin/env ruby

require_relative 'duplicated_files_report'
require_relative 'file_content_duplication_finder'

report = DuplicatedFilesReport.new(FileContentDuplicationFinder.new('folder'))
report.print_data
