#!/usr/bin/env ruby

require_relative 'duplicatedfilecontentfinder'
require_relative 'filecontentduplicationanalyzer'
duplicated_files = DuplicatedFileContentFinder.new(FileContentDuplicationAnalyzer.new('folder'))
duplicated_files.show_duplicated_files
