#!/usr/bin/env ruby

require_relative 'duplicatedfilesreport'
require_relative 'filecontentduplicationfinder'
duplicated_files = DuplicatedFilesReport.new(FileContentDuplicationFinder.new('folder'))
duplicated_files.show_duplicated_files
